### ISSUE TITLE
Unknown type name 'CARingBuffer'  in  CH08-AUGraphInput

### ISSUE THREAD

**Issue by little-dandan** [derekli66/Learning-Core-Audio-Swift-SampleCode#5]
CARingBuffer_Wrapper.cpp:15:5: Unknown type name 'CARingBuffer'

**Comment by derekli66** [comment]
@little-dandan, would you please to check if `CARingBuffer` class exists at the following path?

_/Library/Developer/CoreAudio/PublicUtility/CARingBuffer.cpp_

If you have the book, "**Learning Core Audio**", in the **Footnotes** section, it will introduce you how to install `CARingBuffer`.

In case you don't have the book, you can use "**More Developer Tools...**" menu item on Xcode and find "**Audio Tools for Xcode**" package to install `CARingBuffer`.
